### ISSUE TITLE
How to predict the class in the test dataset?

### ISSUE THREAD

**Issue by twn29004** [Gorilla-Lab-SCUT/frustum-convnet#45]
https://github.com/Gorilla-Lab-SCUT/frustum-convnet/blob/5b1508d3f2140c3c0dd6dd17b5606b532b7a5ec8/train/test_net_det.py#L273
https://github.com/Gorilla-Lab-SCUT/frustum-convnet/blob/5b1508d3f2140c3c0dd6dd17b5606b532b7a5ec8/train/test_net_det.py#L293
In the test_net_det.py , the class_type is from the validation test data label. But in the test dataset, we can't get this info. So How can we get the class in the test dataset.

**Comment by MoreLyxixi** [comment]
您好，这个问题您解决了吗？
